#!/bin/bash
# Upload before/after screenshots to JIRA and add a visual comparison comment
# Usage: bash jira-upload-screenshots.sh <JIRA-KEY> <screenshots-dir> [manifest.json]
#
# Uploads all PNG files in the screenshots directory as JIRA attachments,
# then adds a comment with a visual comparison table.

set -euo pipefail

JIRA_KEY="${1:?Usage: jira-upload-screenshots.sh <JIRA-KEY> <screenshots-dir> [manifest.json]}"
SCREENSHOTS_DIR="${2:?Screenshots directory required}"
MANIFEST="${3:-}"

EMAIL=$(cat ~/.claude/.atlassian-email 2>/dev/null)
TOKEN=$(cat ~/.claude/.atlassian-token 2>/dev/null)
BASE="https://foundingup-dan.atlassian.net"

if [ -z "$EMAIL" ] || [ -z "$TOKEN" ]; then
  echo "Error: Missing Atlassian credentials in ~/.claude/.atlassian-email or ~/.claude/.atlassian-token"
  exit 1
fi

echo "=== Uploading screenshots to $JIRA_KEY ==="

# Upload all PNGs as attachments
UPLOADED=0
for PNG in "$SCREENSHOTS_DIR"/*.png; do
  [ -f "$PNG" ] || continue
  FILENAME=$(basename "$PNG")

  STATUS=$(curl -s -w "%{http_code}" -o /dev/null \
    -u "$EMAIL:$TOKEN" \
    -H "X-Atlassian-Token: no-check" \
    -F "file=@$PNG" \
    "$BASE/rest/api/3/issue/$JIRA_KEY/attachments")

  if [ "$STATUS" = "200" ]; then
    echo "  Uploaded: $FILENAME"
    UPLOADED=$((UPLOADED + 1))
  else
    echo "  FAILED: $FILENAME (HTTP $STATUS)"
  fi
done

echo "  $UPLOADED files uploaded"

# Build comparison comment
if [ -n "$MANIFEST" ] && [ -f "$MANIFEST" ]; then
  echo ""
  echo "=== Adding visual comparison comment ==="

  # Build wiki-markup table from manifest
  COMMENT=$(python3 -c "
import json, os

with open('$MANIFEST') as f:
    m = json.load(f)

lines = ['h2. Visual Review Screenshots', '']
lines.append('|| # || Description || Category || Before || After ||')

for edit in m.get('edits', []):
    eid = edit['id']
    desc = edit.get('description', '')[:50]
    cat = edit.get('category', '')
    before_file = f'{eid}-before.png'
    after_file = f'{eid}-after.png'

    before_dir = '$SCREENSHOTS_DIR'
    has_before = os.path.exists(os.path.join(before_dir, before_file))
    has_after = os.path.exists(os.path.join(before_dir, after_file))

    before_img = f'!{before_file}|thumbnail!' if has_before else '(no screenshot)'
    after_img = f'!{after_file}|thumbnail!' if has_after else '(no screenshot)'

    lines.append(f'| {eid} | {desc} | {cat} | {before_img} | {after_img} |')

lines.append('')
lines.append(f'_Generated by visual-review skill. {len(m.get(\"edits\",[]))} edits reviewed._')
print('\\n'.join(lines))
")

  # Post comment using v2 API (supports wiki markup)
  COMMENT_JSON=$(python3 -c "
import json
print(json.dumps({'body': '''$COMMENT'''}))
")

  STATUS=$(curl -s -w "%{http_code}" -o /dev/null \
    -u "$EMAIL:$TOKEN" \
    -H "Content-Type: application/json" \
    -X POST \
    -d "$COMMENT_JSON" \
    "$BASE/rest/api/2/issue/$JIRA_KEY/comment")

  if [ "$STATUS" = "201" ]; then
    echo "  Comment added with visual comparison table"
  else
    echo "  Comment FAILED (HTTP $STATUS)"
  fi
fi

echo ""
echo "=== Done ==="
echo "  View at: $BASE/browse/$JIRA_KEY"
